Repository algorand/java-algorand-sdk, pull requests merged in 2022-11, with the labels that each got.

#345 Boxes: Add support for Boxes
  src/main/java/com/algorand/algosdk/builder/transaction/ApplicationBaseTransactionBuilder.java
  src/main/java/com/algorand/algosdk/builder/transaction/ApplicationCallReferencesSetter.java
  src/main/java/com/algorand/algosdk/builder/transaction/MethodCallTransactionBuilder.java
  src/main/java/com/algorand/algosdk/transaction/AppBoxReference.java
  src/main/java/com/algorand/algosdk/transaction/MethodCallParams.java
  src/main/java/com/algorand/algosdk/transaction/Transaction.java
  src/main/java/com/algorand/algosdk/util/BoxQueryEncoding.java
  src/main/java/com/algorand/algosdk/v2/client/algod/GetApplicationBoxByName.java
  src/main/java/com/algorand/algosdk/v2/client/algod/GetApplicationBoxes.java
  src/main/java/com/algorand/algosdk/v2/client/common/AlgodClient.java
  src/main/java/com/algorand/algosdk/v2/client/common/Client.java
  src/main/java/com/algorand/algosdk/v2/client/common/IndexerClient.java
  src/main/java/com/algorand/algosdk/v2/client/common/Query.java
  src/main/java/com/algorand/algosdk/v2/client/indexer/LookupApplicationBoxByIDAndName.java
  src/main/java/com/algorand/algosdk/v2/client/indexer/SearchForApplicationBoxes.java
  src/main/java/com/algorand/algosdk/v2/client/model/Account.java
  src/main/java/com/algorand/algosdk/v2/client/model/Box.java
  src/main/java/com/algorand/algosdk/v2/client/model/BoxDescriptor.java
  src/main/java/com/algorand/algosdk/v2/client/model/BoxesResponse.java
  src/test/integration.tags
  src/test/java/com/algorand/algosdk/cucumber/shared/TransactionSteps.java
  src/test/java/com/algorand/algosdk/integration/Applications.java
  src/test/java/com/algorand/algosdk/integration/Clients.java
  src/test/java/com/algorand/algosdk/transaction/TestAppBoxReference.java
  src/test/java/com/algorand/algosdk/transaction/TestBoxReference.java
  src/test/java/com/algorand/algosdk/transaction/TestTransaction.java
  src/test/java/com/algorand/algosdk/unit/AlgodPaths.java
  src/test/java/com/algorand/algosdk/unit/IndexerPaths.java
  src/test/java/com/algorand/algosdk/util/ComparableBytes.java
  src/test/java/com/algorand/algosdk/util/ConversionUtils.java
  src/test/java/com/algorand/algosdk/util/TestBoxQueryEncoding.java
  src/test/unit.tags
Labels: New Feature

#422 SDK: Fix transaction decoding with boxes
  src/main/java/com/algorand/algosdk/transaction/Transaction.java
  src/test/java/com/algorand/algosdk/transaction/TestTransaction.java
Labels: Bug-Fix

#427 BugFix: Fix incorrect reference to global schema
  src/main/java/com/algorand/algosdk/transaction/Transaction.java
Labels: Bug-Fix

#425 Enhancement: Migrate v1 algod dependencies to v2 in cucumber tests
  src/test/java/com/algorand/algosdk/integration/Applications.java
  src/test/java/com/algorand/algosdk/integration/AtomicTxnComposer.java
  src/test/java/com/algorand/algosdk/integration/Clients.java
  src/test/java/com/algorand/algosdk/integration/Stepdefs.java
  src/test/java/com/algorand/algosdk/integration/TransientAccount.java
Labels: Enhancement

#431 Bug-Fix: parsing type strings for tuples containing static arrays of tuples
  src/main/java/com/algorand/algosdk/abi/ABIType.java
  src/test/java/com/algorand/algosdk/abi/TestTypes.java
Labels: Bug-Fix

#432 Enhancement: Allowing zero length in static array
  src/main/java/com/algorand/algosdk/abi/ABIType.java
  src/main/java/com/algorand/algosdk/abi/TypeArrayStatic.java
  src/test/java/com/algorand/algosdk/abi/TestTypes.java
Labels: Enhancement
