Repository algorand/java-algorand-sdk, pull requests merged in 2022-08, with the labels that each got.

#348 AVM: Consolidate TEAL and AVM versions
  src/main/java/com/algorand/algosdk/logic/Logic.java
  src/test/java/com/algorand/algosdk/logic/TestLogic.java
Labels: Enhancement

#350 Testing: Modify cucumber steps to use dev mode network
  Makefile
  src/test/java/com/algorand/algosdk/integration/Applications.java
  src/test/java/com/algorand/algosdk/integration/Stepdefs.java
  src/test/java/com/algorand/algosdk/integration/TransientAccount.java
Labels: Enhancement

#352 DevTools: adding source map decoder
  Makefile
  src/main/java/com/algorand/algosdk/logic/SourceMap.java
  src/test/java/com/algorand/algosdk/integration/Stepdefs.java
  src/test/java/com/algorand/algosdk/unit/TestSourceMap.java
Labels: New Feature

#365 FOR REVIEW ONLY - java-algorand-sdk v1.17.0
  .github/release.yml
  .github/workflows/pr-type-category.yml
  .gitignore
  CHANGELOG.md
  Makefile
  README.md
  pom.xml
  src/main/java/com/algorand/algosdk/logic/Logic.java
  src/main/java/com/algorand/algosdk/logic/SourceMap.java
  src/main/java/com/algorand/algosdk/v2/client/model/Enums.java
  src/test/java/com/algorand/algosdk/integration/Applications.java
  src/test/java/com/algorand/algosdk/integration/Stepdefs.java
  src/test/java/com/algorand/algosdk/integration/TransientAccount.java
  src/test/java/com/algorand/algosdk/logic/TestLogic.java
  src/test/java/com/algorand/algosdk/unit/TestSourceMap.java
  src/test/java/com/algorand/algosdk/util/TestEncoder.java
Labels: Skip-Release-Notes

#363 Enhancement: Use Sandbox for Testing
  .test-env
  Makefile
  README.md
  run_integration_tests.sh
  src/test/integration.tags
  src/test/java/com/algorand/algosdk/integration/Clients.java
  src/test/java/com/algorand/algosdk/integration/EvalDelta.java
  src/test/java/com/algorand/algosdk/integration/Indexer.java
  src/test/java/com/algorand/algosdk/integration/Stepdefs.java
  src/test/unit.tags
  test-harness.sh
Labels: Enhancement

#371 Bug-Fix: Pass verbosity to the harness and sandbox
  test-harness.sh
Labels: Bug-Fix

#367 Enhancement: Deprecating use of langspec
  src/main/java/com/algorand/algosdk/crypto/LogicsigSignature.java
  src/main/java/com/algorand/algosdk/logic/Logic.java
  src/test/java/com/algorand/algosdk/crypto/TestLogicsigSignature.java
  src/test/java/com/algorand/algosdk/unit/ProgramSanityCheck.java
  src/test/unit.tags
Labels: Enhancement

#360 StateProofs: Add State Proof support.
  README.md
  src/main/java/com/algorand/algosdk/transaction/Transaction.java
  src/main/java/com/algorand/algosdk/v2/client/algod/GetLightBlockHeaderProof.java
  src/main/java/com/algorand/algosdk/v2/client/algod/GetStateProof.java
  src/main/java/com/algorand/algosdk/v2/client/algod/GetTransactionProof.java
  src/main/java/com/algorand/algosdk/v2/client/common/AlgodClient.java
  src/main/java/com/algorand/algosdk/v2/client/model/Block.java
  src/main/java/com/algorand/algosdk/v2/client/model/Enums.java
  src/main/java/com/algorand/algosdk/v2/client/model/HashFactory.java
  src/main/java/com/algorand/algosdk/v2/client/model/IndexerStateProofMessage.java
  src/main/java/com/algorand/algosdk/v2/client/model/LightBlockHeaderProof.java
  src/main/java/com/algorand/algosdk/v2/client/model/MerkleArrayProof.java
  src/main/java/com/algorand/algosdk/v2/client/model/StateProof.java
  src/main/java/com/algorand/algosdk/v2/client/model/StateProofFields.java
  src/main/java/com/algorand/algosdk/v2/client/model/StateProofMessage.java
  src/main/java/com/algorand/algosdk/v2/client/model/StateProofParticipant.java
  src/main/java/com/algorand/algosdk/v2/client/model/StateProofReveal.java
  src/main/java/com/algorand/algosdk/v2/client/model/StateProofSigSlot.java
  src/main/java/com/algorand/algosdk/v2/client/model/StateProofSignature.java
  src/main/java/com/algorand/algosdk/v2/client/model/StateProofTracking.java
  src/main/java/com/algorand/algosdk/v2/client/model/StateProofVerifier.java
  src/main/java/com/algorand/algosdk/v2/client/model/Transaction.java
  src/main/java/com/algorand/algosdk/v2/client/model/TransactionProofResponse.java
  src/main/java/com/algorand/algosdk/v2/client/model/TransactionStateProof.java
  src/main/java/com/algorand/algosdk/v2/client/model/VersionBuild.java
  src/test/java/com/algorand/algosdk/unit/AlgodPaths.java
  src/test/java/com/algorand/algosdk/unit/IndexerPaths.java
  src/test/java/com/algorand/algosdk/unit/ResponsesShared.java
  src/test/java/com/algorand/algosdk/unit/RunCucumberUnitTest.java
  src/test/java/com/algorand/algosdk/unit/utils/QueryMapper.java
  src/test/unit.tags
Labels: New Feature
