Repository algorand/java-algorand-sdk, pull requests merged in 2023-05, with the labels that each got.

#559 DevOps: Add CODEOWNERS to restrict workflow editing
  .github/workflows/pr-type-category.yml
  CODEOWNERS
Labels: Enhancement

#561 docs: remove old example from README
  README.md
Labels: Bug-Fix

#571 DevOps: Update CODEOWNERS to only refer to the devops group
  CODEOWNERS
Labels: Enhancement, unplanned, Team Hyper Flow

#578 Enhancement: Verbose Harness
  .test-env
Labels: Skip-Release-Notes
